name: check

on:
  workflow_dispatch:

jobs:
  check:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check code
        run: |
          echo "Checking code..."
          echo "Code is good!" 
          RESULT=${{ secrets.SECRET1 == 'test-env-value' }}
          echo "Secret is valid: $RESULT"
